language: generic
sudo: required
services:
    - docker

before_install:
    - cd DockerAndKubernetes/Section7/complex
    - docker build -t packy1014/complex_client_test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true packy1014/complex_client_test npm test

after_success:
    - docker build -t packy1014/complex_client -f ./client/Dockerfile ./client
    - docker build -t packy1014/complex_nginx -f ./client/Dockerfile ./nginx
    - docker build -t packy1014/complex_server -f ./client/Dockerfile ./server
    - docker build -t packy1014/complex_worker -f ./client/Dockerfile ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push packy1014/complex_client
    - docker push packy1014/complex_nginx
    - docker push packy1014/complex_server
    - docker push packy1014/complex_worker
